/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javawrap6100 */

#ifndef _Included_javawrap6100
#define _Included_javawrap6100
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javawrap6100
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javawrap6100_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     javawrap6100
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javawrap6100_close
  (JNIEnv *, jobject);

/*
 * Class:     javawrap6100
 * Method:    Eject
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_javawrap6100_Eject
  (JNIEnv *, jobject, jint);

/*
 * Class:     javawrap6100
 * Method:    PerformScan
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_javawrap6100_PerformScan
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     javawrap6100
 * Method:    getLastDoc
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_javawrap6100_getLastDoc
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     javawrap6100
 * Method:    getLastMICR
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javawrap6100_getLastMICR
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javawrap6100
 * Method:    getStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javawrap6100_getStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
